name: meme_tabu
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '^3.10.0'

flutter:
  assets:
    - assets/cards.json
 

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  video_player_win: ^3.2.2
  flutter_vlc_player: ^7.0.0
